// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks_test

import mock "github.com/stretchr/testify/mock"

// MessageSender is an autogenerated mock type for the MessageSender type
type MessageSender struct {
	mock.Mock
}

// SendMsg provides a mock function with given fields: msg, deviceTag
func (_m *MessageSender) SendMsg(msg string, deviceTag string) error {
	ret := _m.Called(msg, deviceTag)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(msg, deviceTag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
